---
name: update-sources
on:
  workflow_dispatch:
  schedule:
    # runs every midnight
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          chmod +x update.sh
          ./update.sh
